/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8BarInfo.cpp"
#include "bindings/V8CSSValueList.cpp"
#include "bindings/V8CharacterData.cpp"
#include "bindings/V8Comment.cpp"
#include "bindings/V8CustomEvent.cpp"
#include "bindings/V8DOMParser.cpp"
#include "bindings/V8HTMLAppletElement.cpp"
#include "bindings/V8HTMLBRElement.cpp"
#include "bindings/V8HTMLButtonElement.cpp"
#include "bindings/V8HTMLCanvasElement.cpp"
#include "bindings/V8HTMLDocument.cpp"
#include "bindings/V8HTMLHeadElement.cpp"
#include "bindings/V8HTMLIFrameElement.cpp"
#include "bindings/V8HTMLTableColElement.cpp"
#include "bindings/V8HTMLUListElement.cpp"
#include "bindings/V8KeyboardEvent.cpp"
#include "bindings/V8Node.cpp"
#include "bindings/V8NodeFilter.cpp"
#include "bindings/V8ValidityState.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8WebGLFramebuffer.cpp"
#include "bindings/V8WebGLRenderbuffer.cpp"
#include "bindings/V8WebGLTexture.cpp"
#include "bindings/V8WebGLUniformLocation.cpp"
#endif

#if ENABLE(DATAGRID)
#include "bindings/V8DataGridColumn.cpp"
#include "bindings/V8DataGridColumnList.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8EntryCallback.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBKeyRange.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedLength.cpp"
#include "bindings/V8SVGAnimatedRect.cpp"
#include "bindings/V8SVGDefsElement.cpp"
#include "bindings/V8SVGElement.cpp"
#include "bindings/V8SVGImageElement.cpp"
#include "bindings/V8SVGMatrix.cpp"
#include "bindings/V8SVGNumber.cpp"
#include "bindings/V8SVGPathSeg.cpp"
#include "bindings/V8SVGPathSegClosePath.cpp"
#include "bindings/V8SVGPathSegLinetoHorizontalAbs.cpp"
#include "bindings/V8SVGPathSegList.cpp"
#include "bindings/V8SVGPoint.cpp"
#include "bindings/V8SVGStringList.cpp"
#include "bindings/V8SVGStyleElement.cpp"
#include "bindings/V8SVGTextPathElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEColorMatrixElement.cpp"
#include "bindings/V8SVGFEConvolveMatrixElement.cpp"
#include "bindings/V8SVGFEDiffuseLightingElement.cpp"
#include "bindings/V8SVGFEMergeNodeElement.cpp"
#include "bindings/V8SVGFilterElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGFontFaceElement.cpp"
#endif

#if ENABLE(TOUCH_EVENTS)
#include "bindings/V8Touch.cpp"
#endif

#if ENABLE(WEB_TIMING)
#include "bindings/V8Timing.cpp"
#endif

#if ENABLE(WORKERS)
#include "bindings/V8DedicatedWorkerContext.cpp"
#endif
