/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8Attr.cpp"
#include "bindings/V8Blob.cpp"
#include "bindings/V8BlobBuilder.cpp"
#include "bindings/V8CSSImportRule.cpp"
#include "bindings/V8CSSPageRule.cpp"
#include "bindings/V8DOMFormData.cpp"
#include "bindings/V8Event.cpp"
#include "bindings/V8EventException.cpp"
#include "bindings/V8HTMLAnchorElement.cpp"
#include "bindings/V8HTMLCollection.cpp"
#include "bindings/V8HTMLIsIndexElement.cpp"
#include "bindings/V8HTMLLabelElement.cpp"
#include "bindings/V8HTMLLegendElement.cpp"
#include "bindings/V8HTMLMarqueeElement.cpp"
#include "bindings/V8HTMLOptionElement.cpp"
#include "bindings/V8HTMLParagraphElement.cpp"
#include "bindings/V8Location.cpp"
#include "bindings/V8MediaList.cpp"
#include "bindings/V8PopStateEvent.cpp"
#include "bindings/V8UIEvent.cpp"
#include "bindings/V8WheelEvent.cpp"
#include "bindings/V8XMLHttpRequestUpload.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8ArrayBufferView.cpp"
#include "bindings/V8Uint32Array.cpp"
#include "bindings/V8Uint8Array.cpp"
#include "bindings/V8WebGLProgram.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8SQLResultSet.cpp"
#endif

#if ENABLE(DATAGRID)
#include "bindings/V8HTMLDataGridRowElement.cpp"
#endif

#if ENABLE(DOM_STORAGE)
#include "bindings/V8StorageEvent.cpp"
#endif

#if ENABLE(GEOLOCATION)
#include "bindings/V8Geoposition.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBEvent.cpp"
#include "bindings/V8IDBFactory.cpp"
#endif

#if ENABLE(INSPECTOR)
#include "bindings/V8InjectedScriptHost.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGDescElement.cpp"
#include "bindings/V8SVGEllipseElement.cpp"
#include "bindings/V8SVGMetadataElement.cpp"
#include "bindings/V8SVGPathSegLinetoHorizontalRel.cpp"
#include "bindings/V8SVGPathSegLinetoVerticalRel.cpp"
#include "bindings/V8SVGPathSegMovetoAbs.cpp"
#include "bindings/V8SVGPatternElement.cpp"
#include "bindings/V8SVGRadialGradientElement.cpp"
#include "bindings/V8SVGScriptElement.cpp"
#include "bindings/V8SVGTRefElement.cpp"
#include "bindings/V8SVGTSpanElement.cpp"
#include "bindings/V8SVGViewElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGComponentTransferFunctionElement.cpp"
#include "bindings/V8SVGFEDisplacementMapElement.cpp"
#include "bindings/V8SVGFEFuncAElement.cpp"
#include "bindings/V8SVGFEImageElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_ANIMATION)
#include "bindings/V8SVGAnimateTransformElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGFontElement.cpp"
#include "bindings/V8SVGFontFaceFormatElement.cpp"
#include "bindings/V8SVGFontFaceUriElement.cpp"
#endif

#if ENABLE(TOUCH_EVENTS)
#include "bindings/V8TouchEvent.cpp"
#endif
