/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CSSCharsetRule.cpp"
#include "bindings/V8CSSStyleDeclaration.cpp"
#include "bindings/V8CanvasPattern.cpp"
#include "bindings/V8DOMMimeType.cpp"
#include "bindings/V8DocumentType.cpp"
#include "bindings/V8Element.cpp"
#include "bindings/V8Entity.cpp"
#include "bindings/V8EntityReference.cpp"
#include "bindings/V8HTMLBaseElement.cpp"
#include "bindings/V8HTMLBlockquoteElement.cpp"
#include "bindings/V8HTMLDListElement.cpp"
#include "bindings/V8HTMLFontElement.cpp"
#include "bindings/V8HTMLHeadingElement.cpp"
#include "bindings/V8HTMLHtmlElement.cpp"
#include "bindings/V8HTMLInputElement.cpp"
#include "bindings/V8HTMLLIElement.cpp"
#include "bindings/V8HTMLMapElement.cpp"
#include "bindings/V8HTMLMetaElement.cpp"
#include "bindings/V8HTMLObjectElement.cpp"
#include "bindings/V8HTMLScriptElement.cpp"
#include "bindings/V8History.cpp"
#include "bindings/V8MemoryInfo.cpp"
#include "bindings/V8NamedNodeMap.cpp"
#include "bindings/V8PageTransitionEvent.cpp"
#include "bindings/V8WebKitCSSMatrix.cpp"
#include "bindings/V8WebKitPoint.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8Uint16Array.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8Database.cpp"
#include "bindings/V8SQLTransactionSync.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8Metadata.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBDatabaseException.cpp"
#include "bindings/V8IDBObjectStore.cpp"
#include "bindings/V8IDBSuccessEvent.cpp"
#include "bindings/V8IDBTransaction.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAngle.cpp"
#include "bindings/V8SVGAnimatedNumber.cpp"
#include "bindings/V8SVGAnimatedNumberList.cpp"
#include "bindings/V8SVGLength.cpp"
#include "bindings/V8SVGLengthList.cpp"
#include "bindings/V8SVGLinearGradientElement.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicAbs.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicSmoothAbs.cpp"
#include "bindings/V8SVGPathSegLinetoRel.cpp"
#include "bindings/V8SVGTitleElement.cpp"
#include "bindings/V8SVGUnitTypes.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEPointLightElement.cpp"
#include "bindings/V8SVGFETileElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGAltGlyphElement.cpp"
#endif

#if ENABLE(SVG_ANIMATION)
#include "bindings/V8SVGAnimationElement.cpp"
#include "bindings/V8SVGSetElement.cpp"
#endif

#if ENABLE(VIDEO)
#include "bindings/V8HTMLMediaElement.cpp"
#include "bindings/V8TimeRanges.cpp"
#endif
