/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
*/

#if ENABLE(DEVICE_ORIENTATION)

#ifndef V8DeviceOrientationEvent_h
#define V8DeviceOrientationEvent_h

#include "DeviceOrientationEvent.h"
#include "WrapperTypeInfo.h"
#include "wtf/text/StringHash.h"
#include <v8.h>
#include <wtf/HashMap.h>

namespace WebCore {

class V8DeviceOrientationEvent {

public:
    static bool HasInstance(v8::Handle<v8::Value> value);
    static v8::Persistent<v8::FunctionTemplate> GetRawTemplate();
    static v8::Persistent<v8::FunctionTemplate> GetTemplate();
    static DeviceOrientationEvent* toNative(v8::Handle<v8::Object>);
    static v8::Handle<v8::Object> wrap(DeviceOrientationEvent*);
    static void derefObject(void*);
    static WrapperTypeInfo info;
    static v8::Handle<v8::Value> initDeviceOrientationEventCallback(const v8::Arguments&);
    static v8::Handle<v8::Value> alphaAccessorGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info);
    static void alphaAccessorSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
    static v8::Handle<v8::Value> betaAccessorGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info);
    static void betaAccessorSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
    static v8::Handle<v8::Value> gammaAccessorGetter(v8::Local<v8::String> name, const v8::AccessorInfo& info);
    static void gammaAccessorSetter(v8::Local<v8::String> name, v8::Local<v8::Value> value, const v8::AccessorInfo& info);
    static const int internalFieldCount = v8DefaultWrapperInternalFieldCount + 0;
};

v8::Handle<v8::Value> toV8(DeviceOrientationEvent*);
v8::Handle<v8::Value> toV8(PassRefPtr<DeviceOrientationEvent >);
}

#endif // V8DeviceOrientationEvent_h
#endif // ENABLE(DEVICE_ORIENTATION)

