/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CSSVariablesDeclaration.cpp"
#include "bindings/V8CanvasPixelArray.cpp"
#include "bindings/V8CanvasRenderingContext.cpp"
#include "bindings/V8CanvasRenderingContext2D.cpp"
#include "bindings/V8Clipboard.cpp"
#include "bindings/V8Counter.cpp"
#include "bindings/V8DOMImplementation.cpp"
#include "bindings/V8DOMMimeTypeArray.cpp"
#include "bindings/V8Document.cpp"
#include "bindings/V8DocumentFragment.cpp"
#include "bindings/V8HTMLAreaElement.cpp"
#include "bindings/V8HTMLQuoteElement.cpp"
#include "bindings/V8HTMLTableCellElement.cpp"
#include "bindings/V8HTMLTableElement.cpp"
#include "bindings/V8MessageEvent.cpp"
#include "bindings/V8MessagePort.cpp"
#include "bindings/V8OverflowEvent.cpp"
#include "bindings/V8StyleMedia.cpp"
#include "bindings/V8TextMetrics.cpp"
#include "bindings/V8WebKitCSSTransformValue.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8Int16Array.cpp"
#include "bindings/V8WebGLRenderingContext.cpp"
#include "bindings/V8WebGLShader.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8SQLException.cpp"
#include "bindings/V8SQLStatementErrorCallback.cpp"
#include "bindings/V8SQLTransactionCallback.cpp"
#endif

#if ENABLE(DATAGRID)
#include "bindings/V8HTMLDataGridColElement.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8DirectoryReader.cpp"
#include "bindings/V8FileEntry.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBDatabase.cpp"
#endif

#if ENABLE(JAVASCRIPT_DEBUGGER)
#include "bindings/V8JavaScriptCallFrame.cpp"
#endif

#if ENABLE(OFFLINE_WEB_APPLICATIONS)
#include "bindings/V8DOMApplicationCache.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedInteger.cpp"
#include "bindings/V8SVGAnimatedString.cpp"
#include "bindings/V8SVGAnimatedTransformList.cpp"
#include "bindings/V8SVGColor.cpp"
#include "bindings/V8SVGPathElement.cpp"
#include "bindings/V8SVGPathSegArcRel.cpp"
#include "bindings/V8SVGPathSegCurvetoQuadraticAbs.cpp"
#include "bindings/V8SVGPathSegCurvetoQuadraticSmoothAbs.cpp"
#include "bindings/V8SVGRect.cpp"
#include "bindings/V8SVGTextContentElement.cpp"
#include "bindings/V8SVGTextElement.cpp"
#include "bindings/V8SVGTextPositioningElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEBlendElement.cpp"
#include "bindings/V8SVGFECompositeElement.cpp"
#include "bindings/V8SVGFEFuncGElement.cpp"
#include "bindings/V8SVGFEMorphologyElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGFontFaceNameElement.cpp"
#include "bindings/V8SVGGlyphElement.cpp"
#include "bindings/V8SVGVKernElement.cpp"
#endif
