/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8CSSPrimitiveValue.cpp"
#include "bindings/V8CSSStyleRule.cpp"
#include "bindings/V8Coordinates.cpp"
#include "bindings/V8DOMStringList.cpp"
#include "bindings/V8File.cpp"
#include "bindings/V8FileList.cpp"
#include "bindings/V8HTMLBaseFontElement.cpp"
#include "bindings/V8HTMLDivElement.cpp"
#include "bindings/V8HTMLElement.cpp"
#include "bindings/V8HTMLFieldSetElement.cpp"
#include "bindings/V8HTMLHRElement.cpp"
#include "bindings/V8HTMLImageElement.cpp"
#include "bindings/V8HTMLLinkElement.cpp"
#include "bindings/V8HTMLOListElement.cpp"
#include "bindings/V8HTMLOptGroupElement.cpp"
#include "bindings/V8HTMLOptionsCollection.cpp"
#include "bindings/V8HTMLParamElement.cpp"
#include "bindings/V8HTMLTableRowElement.cpp"
#include "bindings/V8ImageData.cpp"
#include "bindings/V8NodeIterator.cpp"
#include "bindings/V8Notation.cpp"
#include "bindings/V8ProcessingInstruction.cpp"
#include "bindings/V8ProgressEvent.cpp"
#include "bindings/V8RGBColor.cpp"
#include "bindings/V8Rect.cpp"
#include "bindings/V8StyleSheetList.cpp"
#include "bindings/V8TextEvent.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8WebGLActiveInfo.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8SQLError.cpp"
#endif

#if ENABLE(DATAGRID)
#include "bindings/V8HTMLDataGridCellElement.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8EntriesCallback.cpp"
#include "bindings/V8ErrorCallback.cpp"
#endif

#if ENABLE(METER_TAG)
#include "bindings/V8HTMLMeterElement.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAElement.cpp"
#include "bindings/V8SVGAnimatedAngle.cpp"
#include "bindings/V8SVGPaint.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicRel.cpp"
#include "bindings/V8SVGPathSegCurvetoQuadraticSmoothRel.cpp"
#include "bindings/V8SVGRenderingIntent.cpp"
#include "bindings/V8SVGTransform.cpp"
#include "bindings/V8SVGTransformList.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEOffsetElement.cpp"
#include "bindings/V8SVGFESpecularLightingElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FONTS)
#include "bindings/V8SVGMissingGlyphElement.cpp"
#endif

#if ENABLE(SVG_ANIMATION)
#include "bindings/V8SVGAnimateColorElement.cpp"
#endif

#if ENABLE(WORKERS)
#include "bindings/V8AbstractWorker.cpp"
#include "bindings/V8WorkerContext.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathException.cpp"
#endif
