/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8BeforeProcessEvent.cpp"
#include "bindings/V8CSSVariablesRule.cpp"
#include "bindings/V8CanvasGradient.cpp"
#include "bindings/V8CompositionEvent.cpp"
#include "bindings/V8DOMPluginArray.cpp"
#include "bindings/V8DOMSelection.cpp"
#include "bindings/V8HTMLBodyElement.cpp"
#include "bindings/V8HTMLEmbedElement.cpp"
#include "bindings/V8HTMLFrameElement.cpp"
#include "bindings/V8HTMLStyleElement.cpp"
#include "bindings/V8MutationEvent.cpp"
#include "bindings/V8Navigator.cpp"
#include "bindings/V8Range.cpp"
#include "bindings/V8Screen.cpp"
#include "bindings/V8StyleSheet.cpp"
#include "bindings/V8WebKitCSSKeyframesRule.cpp"
#include "bindings/V8XMLHttpRequestException.cpp"
#include "bindings/V8XMLHttpRequestProgressEvent.cpp"
#include "bindings/V8XMLSerializer.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8ArrayBuffer.cpp"
#include "bindings/V8WebGLBuffer.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8DatabaseCallback.cpp"
#include "bindings/V8DatabaseSync.cpp"
#include "bindings/V8SQLStatementCallback.cpp"
#include "bindings/V8SQLTransaction.cpp"
#include "bindings/V8SQLTransactionSyncCallback.cpp"
#endif

#if ENABLE(DATAGRID)
#include "bindings/V8HTMLDataGridElement.cpp"
#endif

#if ENABLE(DATALIST)
#include "bindings/V8HTMLDataListElement.cpp"
#endif

#if ENABLE(DEVICE_ORIENTATION)
#include "bindings/V8DeviceOrientationEvent.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8FileSystemCallback.cpp"
#include "bindings/V8MetadataCallback.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBDatabaseError.cpp"
#include "bindings/V8IDBKey.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGCircleElement.cpp"
#include "bindings/V8SVGDocument.cpp"
#include "bindings/V8SVGLineElement.cpp"
#include "bindings/V8SVGPathSegArcAbs.cpp"
#include "bindings/V8SVGPathSegCurvetoCubicSmoothRel.cpp"
#include "bindings/V8SVGPathSegCurvetoQuadraticRel.cpp"
#include "bindings/V8SVGPathSegLinetoAbs.cpp"
#include "bindings/V8SVGRectElement.cpp"
#include "bindings/V8SVGSwitchElement.cpp"
#include "bindings/V8SVGSymbolElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_FOREIGN_OBJECT)
#include "bindings/V8SVGForeignObjectElement.cpp"
#endif

#if ENABLE(WORKERS)
#include "bindings/V8WorkerNavigator.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathEvaluator.cpp"
#endif
