/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the make_jni_lists.py script.
 *
 * Copyright (C) 2009 Google Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define NO_IMPLICIT_ATOMICSTRING

#include "bindings/V8BeforeLoadEvent.cpp"
#include "bindings/V8CDATASection.cpp"
#include "bindings/V8CSSFontFaceRule.cpp"
#include "bindings/V8CSSRule.cpp"
#include "bindings/V8CSSRuleList.cpp"
#include "bindings/V8CSSStyleSheet.cpp"
#include "bindings/V8CSSValue.cpp"
#include "bindings/V8Console.cpp"
#include "bindings/V8DOMCoreException.cpp"
#include "bindings/V8DOMPlugin.cpp"
#include "bindings/V8HTMLDirectoryElement.cpp"
#include "bindings/V8HTMLFormElement.cpp"
#include "bindings/V8HTMLPreElement.cpp"
#include "bindings/V8HTMLSelectElement.cpp"
#include "bindings/V8HTMLTableCaptionElement.cpp"
#include "bindings/V8HTMLTextAreaElement.cpp"
#include "bindings/V8MessageChannel.cpp"
#include "bindings/V8NodeList.cpp"
#include "bindings/V8RangeException.cpp"
#include "bindings/V8TreeWalker.cpp"
#include "bindings/V8WebKitAnimationEvent.cpp"
#include "bindings/V8WebKitCSSKeyframeRule.cpp"
#include "bindings/V8WebKitTransitionEvent.cpp"
#include "bindings/V8XMLHttpRequest.cpp"

#if ENABLE(3D_CANVAS)
#include "bindings/V8Float32Array.cpp"
#endif

#if ENABLE(DATABASE)
#include "bindings/V8SQLResultSetRowList.cpp"
#include "bindings/V8SQLTransactionErrorCallback.cpp"
#endif

#if ENABLE(DOM_STORAGE)
#include "bindings/V8Storage.cpp"
#endif

#if ENABLE(EVENTSOURCE)
#include "bindings/V8EventSource.cpp"
#endif

#if ENABLE(FILE_SYSTEM)
#include "bindings/V8DOMFileSystem.cpp"
#include "bindings/V8Flags.cpp"
#endif

#if ENABLE(GEOLOCATION)
#include "bindings/V8PositionError.cpp"
#endif

#if ENABLE(INDEXED_DATABASE)
#include "bindings/V8IDBCursor.cpp"
#include "bindings/V8IDBErrorEvent.cpp"
#include "bindings/V8IDBRequest.cpp"
#endif

#if ENABLE(INSPECTOR)
#include "bindings/V8InspectorFrontendHost.cpp"
#endif

#if ENABLE(NOTIFICATIONS)
#include "bindings/V8NotificationCenter.cpp"
#endif

#if ENABLE(SVG)
#include "bindings/V8SVGAnimatedEnumeration.cpp"
#include "bindings/V8SVGAnimatedLengthList.cpp"
#include "bindings/V8SVGAnimatedPreserveAspectRatio.cpp"
#include "bindings/V8SVGCursorElement.cpp"
#include "bindings/V8SVGGElement.cpp"
#include "bindings/V8SVGGradientElement.cpp"
#include "bindings/V8SVGMarkerElement.cpp"
#include "bindings/V8SVGMaskElement.cpp"
#include "bindings/V8SVGNumberList.cpp"
#include "bindings/V8SVGPathSegLinetoVerticalAbs.cpp"
#include "bindings/V8SVGPathSegMovetoRel.cpp"
#include "bindings/V8SVGPointList.cpp"
#include "bindings/V8SVGPolylineElement.cpp"
#include "bindings/V8SVGStopElement.cpp"
#include "bindings/V8SVGUseElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(FILTERS)
#include "bindings/V8SVGFEComponentTransferElement.cpp"
#include "bindings/V8SVGFEDistantLightElement.cpp"
#include "bindings/V8SVGFEFloodElement.cpp"
#include "bindings/V8SVGFEFuncBElement.cpp"
#include "bindings/V8SVGFEFuncRElement.cpp"
#include "bindings/V8SVGFEMergeElement.cpp"
#include "bindings/V8SVGFESpotLightElement.cpp"
#include "bindings/V8SVGFETurbulenceElement.cpp"
#endif

#if ENABLE(SVG) && ENABLE(SVG_ANIMATION)
#include "bindings/V8SVGAnimateElement.cpp"
#endif

#if ENABLE(TOUCH_EVENTS)
#include "bindings/V8TouchList.cpp"
#endif

#if ENABLE(VIDEO)
#include "bindings/V8HTMLVideoElement.cpp"
#include "bindings/V8MediaError.cpp"
#endif

#if ENABLE(WEB_SOCKETS)
#include "bindings/V8WebSocket.cpp"
#endif

#if ENABLE(WEB_TIMING)
#include "bindings/V8Navigation.cpp"
#endif

#if ENABLE(WORKERS)
#include "bindings/V8ErrorEvent.cpp"
#include "bindings/V8Worker.cpp"
#endif

#if ENABLE(XPATH)
#include "bindings/V8XPathExpression.cpp"
#endif

#if ENABLE(XSLT)
#include "bindings/V8XSLTProcessor.cpp"
#endif
